### ISSUE TITLE
get-involved-get-started headers

### ISSUE THREAD

**Issue by madhens** [madhens/ubuntu-mate.org#6]
In the `hacktoberfest` branch, in `pages/get-involved-get-started.md`, create the following level 2 headers

Create a Launchpad Account
Create an Ubuntu MATE Community Account
Introduce Yourself in the New Contributor's Thread
Explore The Different Ways to Get Involved

**Comment by juyoungk23** [comment]
Hey @madhens , I'd like to contribute to this! Could you assign this to me? Thanks in advance

**Comment by madhens** [comment]
> Hey @madhens , I'd like to contribute to this! Could you assign this to me? Thanks in advance

Hi! If you'd like to join the Hacktoberfest group that's working with us, go to https://organize.mlh.io/events/4599-hacktoberfest-documentation-meetup-closing-event . I am working to be sure there are enough small pull requests for those who want to have their four PRs, and having you in the group will let me know how many Issues I need to open. We're also having one more meeting next Saturday as a wrap-up, since we'll be continuing this project long-term. So, tl;dr, if you'd like to help contribute, just sign up at the link!
