### ISSUE TITLE
Add headers to get-involved-overview in hacktoberfest branch

### ISSUE THREAD

**Issue by madhens** [madhens/ubuntu-mate.org#7]
In the `hacktoberfest` branch, in `pages/get-involved-overview.md`, add the following level 2 headers:

Invitation
Benefits of Contributing
Why We Need You

**Comment by cdalangin** [comment]
Hi! Can I do this? And I just have to do the headers right?

**Comment by nazuk27** [comment]
Can you please assign this to me?

**Comment by madhens** [comment]
Hello! We're participating with a small Hacktoberfest group, so if you'd like to join, please register at the following link! https://organize.mlh.io/events/4599-hacktoberfest-documentation-meetup-closing-event
